apiVersion: v1
kind: Service
metadata:
  name: ttrend-app-service
  namespace: myfirstns
spec:
  type: NodePort
  selector:
    app: ttrend-app
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000
